#D-D
/gps/source/intensity 1
/gps/particle neutron
/gps/pos/type Beam
/gps/pos/shape Circle
/gps/pos/centre 0 0 200 cm
/gps/pos/radius 2 cm
/gps/ang/type beam1d
/gps/ang/sigma_r 5. deg
/gps/ene/type Gauss
# Do NOT use /gps/energy to set the energy. Documentation says /gps/energy === /gps/ene/mono but they are not.
# /gps/energy forces mono distribution, /gps/ene/mono does not (for what reason????)
# Also if you run /gps/source/list you can ignore the "Energy" row, it is just plain incorrect.
# The energy row shows the previous shot particle's energy, which is 1 MeV if you have not shot anything. - Lars
/gps/ene/mono 2.5 MeV
/gps/ene/sigma 0.1 MeV

# /gps/source/add 0
# /gps/particle gamma
# /gps/pos/type Beam
# /gps/pos/shape Circle
# /gps/pos/centre 0 0 200 cm
# /gps/pos/radius 2 cm
# /gps/ang/type beam1d
# /gps/ang/sigma_r 5. deg
# /gps/ene/type Gauss
# /gps/ene/ezero 2.5 MeV
# /gps/ene/sigma 0 MeV